/**
 * @file content.js
 * @brief Pools de contenu francophones (posts, citations, bios, tags, dégradés…)
 *        dans l'esprit « carnet social » de la maquette Breezy.
 */

export const TEXT_POSTS = [
  "Hier soir, le ciel était parfait — la couleur exacte d'un vieux papier journal.",
  'Question naïve du jour : pourquoi le bon design semble toujours évident seulement après ?',
  'Petite victoire : trois pages écrites avant le café. Le reste de la journée est en bonus.',
  "On sous-estime le pouvoir d'une marche sans téléphone.",
  "Relu mes notes de janvier. J'avais raison sur tout, sauf sur l'essentiel.",
  "Le silence d'un dimanche matin vaut tous les playlists du monde.",
  "Apprendre lentement, c'est apprendre deux fois.",
  'Un carnet, un crayon, une fenêtre. Programme complet.',
  'La typographie change tout. La même phrase, deux émotions.',
  "Je crois que je collectionne les débuts de projets plus que les fins.",
  "Aujourd'hui : ranger pour ne pas écrire. Demain : écrire pour ne pas ranger.",
  "Les meilleures idées arrivent toujours dans la file d'attente de la boulangerie.",
  "Tester moins d'outils, finir plus de choses.",
  'Le café refroidi est le prix de la concentration.',
  'Parfois la contrainte est plus généreuse que la liberté.',
  "J'ai remplacé « il faut que » par « j'ai envie de ». Ça change la semaine.",
  "Une bonne lumière rend n'importe quelle pièce habitable.",
  "Écrire court, c'est respecter le temps des autres.",
  'Le doute fait partie du métier. Le perfectionnisme, non.',
  "Marcher, c'est penser avec les jambes.",
  "Nouvelle recette testée ce soir : risotto aux champignons des bois. Verdict : un succès total.",
  "Le week-end commence par un marché, une baguette et un journal. Rien de plus.",
  "Mon chat a décidé que mon clavier était son lit préféré. Productivité au plus bas.",
  "Premier trail de l'année demain matin. La montagne nous attend.",
  "Série terminée en un week-end. Je n'ai aucun regret.",
  "On a tendance à complexifier ce qui devrait rester simple.",
  "Trois heures de code pour un bug de virgule. C'est la vie du développeur.",
  "La nature est le meilleur antidote au bruit numérique.",
  "Finalement décidé de me remettre au dessin. Le trait hésite, mais il revient.",
  "Un livre par semaine, c'est un objectif raisonnable et transformateur.",
  "Ce matin, j'ai vu un héron sur le canal. Journée bénie.",
  "La cuisine végétale n'est pas un sacrifice, c'est une découverte.",
  "Rencontré quelqu'un d'incroyable aujourd'hui. Le hasard fait bien les choses.",
  "Réinstallé Arch Linux pour la énième fois. Cette fois c'est la bonne.",
  "Le jazz du dimanche après-midi est une institution à ne pas négliger.",
  "Parfois un thé, une bougie et du silence valent une thérapie.",
  "L'IA génère, mais l'humain ressent. Cette nuance compte.",
  "Pas de réseaux sociaux avant 10h. Ma règle d'or de l'année.",
  "Portfolio enfin mis à jour. Seulement six mois de retard.",
  "La pluie sur Paris a quelque chose de cinématographique.",
  "Medias, réseaux, notifications — apprendre à tout éteindre reste un art.",
  "Appris à faire du pain au levain. La cuisine comme alchimie.",
  "Ce projet freelance me tient en haleine depuis trois semaines. Bientôt fini.",
  "Photographier l'ordinaire, c'est lui donner une valeur extraordinaire.",
  "Le vélo en ville recadre la relation à l'espace et au temps.",
  "Retrouvé une vieille playlist. Chaque chanson, une époque.",
  "On ne réalise pas combien une bonne chaise de bureau change la journée.",
  "Verre de vin naturel, planche de fromages, longue conversation. Voilà un bon vendredi.",
  "Cinq minutes de méditation le matin et la journée prend une autre couleur.",
  "Lu un article fascinant sur la mémoire des arbres. La science est poétique.",
  "Vacances sans écrans : radicalement dépaysant et étrangement ressourçant.",
  "Nouveau terminal configuré. La vie est trop courte pour un mauvais setup.",
  "Le meilleur moment de la journée : juste avant que tout le monde se réveille.",
  "Exposé mes aquarelles pour la première fois. Trac et fierté mêlés.",
  "Printemps : les terrasses s'ouvrent, les humeurs changent.",
  "Réappris à ne rien faire. Exercice sous-estimé et fondamental.",
  "Si tu n'as pas de plante verte chez toi, commence par là.",
  "L'architecture de cette ville ne cesse de me surprendre.",
  "Terminé mon premier marathon. Le corps dit non, la tête dit encore.",
  "Petit thread sur ce que j'ai appris en deux ans de freelance : facturer son temps, pas ses heures.",
  "Le débat IA vs créativité humaine me fatigue. Les deux peuvent coexister, soyons sérieux.",
  "Migré tout mon stack vers TypeScript. Aucun regret, que des types.",
  "On parle beaucoup de productivité, rarement de repos. Pourtant l'un ne va pas sans l'autre.",
  "Découvert un café de quartier avec le meilleur flat white de la ville. Adresse en MP.",
  "Le minimalisme n'est pas vide, c'est de l'espace pour ce qui compte.",
  "Conférence inspirante aujourd'hui sur le design éthique. On en ressort changé.",
  "Premier potager sur le balcon : trois tomates, une immense fierté.",
  "Relire un classique à dix ans d'intervalle, c'est lire un autre livre.",
  "La meilleure feature, c'est souvent celle qu'on n'ajoute pas.",
  "Concert hier soir, encore des frissons ce matin. La musique live, rien ne la remplace.",
  "J'ai supprimé trois apps de mon téléphone. Mon attention me remercie déjà.",
  "Le télétravail m'a appris une chose : la discipline vaut mieux que la motivation.",
  "Expo photo ce week-end, mes cinq tirages préférés sont enfin au mur.",
  "Apprendre une langue à l'âge adulte, c'est redevenir humble. J'adore ça.",
  "Le bon code se lit comme une bonne phrase : sans avoir à le relire deux fois.",
  "Randonnée de 20 km aujourd'hui. Les jambes parlent, l'esprit se tait enfin.",
  "On surestime ce qu'on peut faire en un jour, on sous-estime ce qu'on peut faire en un an.",
  "Nouvelle saison de ma série préférée. Soirée canapé non négociable.",
  "Le café du matin est un rituel, pas une dépendance. (Je me mens peut-être.)",
  "Atelier céramique terminé : mes mains se souviennent de la terre.",
  "Investir dans une bonne paire de chaussures, c'est investir dans toutes ses marches futures.",
  "La curiosité ne se gère pas, elle se nourrit.",
];

export const QUOTES = [
  ["« On ne pense pas en marchant — on pense parce qu'on a marché. »", 'Frédéric Gros'],
  ['« La simplicité est la sophistication suprême. »', 'Léonard de Vinci'],
  ['« Ce qui se conçoit bien s\'énonce clairement. »', 'Boileau'],
  ["« Le design, c'est l'art de rendre l'évident invisible. »", 'anonyme'],
  ["« Un objectif sans plan n'est qu'un souhait. »", 'Antoine de Saint-Exupéry'],
  ['« Le mieux est l\'ennemi du bien. »', 'Voltaire'],
  ['« La créativité, c\'est l\'intelligence qui s\'amuse. »', 'Albert Einstein'],
  ["« Tout ce que je sais, c'est que je ne sais rien. »", 'Socrate'],
  ['« La vie est courte, l\'art est long. »', 'Hippocrate'],
  ['« Il n\'y a pas de vent favorable pour celui qui ne sait pas où il va. »', 'Sénèque'],
  ["« Le courage, c'est de chercher la vérité et de la dire. »", 'Jean Jaurès'],
  ['« Sois le changement que tu veux voir dans le monde. »', 'Gandhi'],
];

export const IMAGE_CAPTIONS = [
  "Petits essais d'aquarelle ce matin. Le bleu m'échappe encore.",
  'Atelier ouvert tout le week-end — passez si vous êtes dans le coin.',
  'Lumière de fin de journée sur les toits.',
  'Croquis du jour, sans prétention.',
  'Trouvé ce carnet dans une brocante. Parfait.',
  'La ville sous la pluie a une autre texture.',
  'Vue depuis la terrasse ce matin. Impayable.',
  'Marché du dimanche, couleurs de saison.',
  'Atelier poterie : première pièce ratée, deuxième prometteuse.',
  'Balade vélo sur les quais. Le soleil était au rendez-vous.',
  'Photo argentique développée hier. Le grain, rien ne le remplace.',
  'Cuisine ouverte ce soir — les odeurs envahissent tout.',
];

export const BIOS = [
  'Écrit des notes, lit des cartes, dessine des machines.',
  'Designer le jour, lecteur la nuit.',
  'Je cultive des idées et quelques plantes.',
  'Photographe amateur, marcheur professionnel.',
  'Développeuse, amatrice de typographie et de thé.',
  'Architecte de petites choses utiles.',
  'Apprenti philosophe du quotidien.',
  'Je collectionne les couchers de soleil.',
  'Curieuse de tout, spécialiste de rien.',
  'Carnets, encre, et longues phrases.',
  'Ingénieur le jour, cuisinier le soir.',
  'Passionnée de randonnée et de code propre.',
  'Lectrice compulsive et grande buveuse de thé.',
  'Musicien amateur, amateur de silence.',
  'Graphiste indépendant basé à Lyon.',
  "Court le matin, code l'après-midi.",
  'Jardine les week-ends, déploie en prod la semaine.',
  'Fan de jazz et d\'architecture brutaliste.',
  'Journaliste pigiste, toujours en quête du bon angle.',
  'Enseignante passionnée par les langues.',
  '',
  '',
];

export const TAGS = [
  'carnetdumois', 'lecture', 'design', 'typographie', 'aquarelle', 'photo',
  'café', 'marche', 'minimalisme', 'écriture', 'lumière', 'ville',
  'matin', 'idées', 'atelier', 'nature', 'musique', 'voyage',
  'cuisine', 'sport', 'tech', 'art', 'cinéma', 'jardinage',
  'vélo', 'montagne', 'mer', 'code', 'ia', 'meditation',
  'livre', 'podcast', 'trail', 'photographie', 'architecture',
];

export const GRADIENTS = [
  'linear-gradient(135deg,#FF6F59,#C2412B)', // corail → brique
  'linear-gradient(135deg,#3E7C5A,#1F4D38)', // mousse profonde
  'linear-gradient(135deg,#2F8E86,#185A55)', // sapin / teal
  'linear-gradient(135deg,#D69A3A,#A86A1E)', // ocre doré
  'linear-gradient(135deg,#B5503A,#7C2D1E)', // terracotta
  'linear-gradient(135deg,#4E6E92,#2C3F55)', // bleu ardoise
  'linear-gradient(135deg,#C2502E,#FF7A66)', // brique → corail
  'linear-gradient(135deg,#5C7C5A,#34503A)', // sauge
  'linear-gradient(135deg,#E0A458,#C2502E)', // sable → brique
  'linear-gradient(135deg,#3E6FA3,#27496D)', // bleu encre
  'linear-gradient(135deg,#8A5A6A,#5A3645)', // prune douce
  'linear-gradient(135deg,#D98A4E,#A85A2E)', // abricot brûlé
  'linear-gradient(135deg,#E5E2D8,#C2BFB2)', // papier (clair)
  'linear-gradient(135deg,#2E7D78,#3E7C5A)', // teal → mousse
];

export const COMMENTS = [
  'Tellement vrai.', "J'adore.", 'Merci pour le partage !', 'Ça résonne fort.',
  'Belle prise.', 'D\'accord à 100 %.', 'Tu lis dans mes pensées.', 'Magnifique.',
  'Hâte de voir la suite.', 'Très juste.', 'Note prise.', 'Inspirant, merci.',
  'Je garde ça en tête.', "Exactement ce dont j'avais besoin aujourd'hui.",
  'Super contenu, merci !', 'Pareil de mon côté.', 'Tu m\'as convaincu.',
  'Je partage totalement.', 'Ça fait du bien à lire.', 'Bookmarké pour plus tard.',
  'Toujours aussi pertinent.', 'On en reparlera autour d\'un café.',
  'Bien dit !', 'Félicitations !', 'Continue comme ça.', 'Tu as tout compris.',
  'C\'est exactement ça.', 'Beau travail.', 'J\'ai appris quelque chose.',
  'À mettre en pratique dès demain.',
  'Quel match hier !', 'Allez les Bleus !', 'On y croit pour la finale.',
  'Cette canicule est insupportable…', 'Même ressenti devant le match.',
  'Vivement la prochaine étape du Tour.', 'L\'ambiance était folle hier soir.',
];

export const REPLIES = [
  'Complètement d\'accord avec toi !',
  'Ah oui, je n\'avais pas pensé à ça.',
  'Tu as raison, c\'est plus simple comme ça.',
  'Merci pour la précision.',
  'Haha exactement ce que je pensais !',
  'C\'est une bonne idée en fait.',
  'Je vais essayer ça.',
  'Pareil pour moi !',
  'On est sur la même longueur d\'onde.',
  'Bien vu.',
  'Super réponse.',
  'Ça m\'aide beaucoup, merci.',
  'J\'avais le même ressenti.',
  'Trop vrai.',
  'C\'est noté !',
  'Excellent point.',
  'Je plussoie à fond.',
  'Et dire que je n\'y avais pas pensé…',
  'Voilà qui est clair.',
  'Bonne question d\'ailleurs.',
  'Exactement ce qu\'il fallait dire.',
  'Tu m\'enlèves les mots de la bouche.',
  'On revoit ça ensemble ?',
  'Totalement d\'accord.',
  'Un grand merci pour ça.',
  'Ah intéressant !',
  'C\'est logique finalement.',
  'Je vais y réfléchir.',
  'Tu m\'as convaincu là.',
  'Bonne observation.',
];
